export const ADD_CHANNEL_PARTNER_PROFILE_REQUEST =
  "ADD_CHANNEL_PARTNER_PROFILE_REQUEST";
export const ADD_CHANNEL_PARTNER_PROFILE_SUCCESS =
  "ADD_CHANNEL_PARTNER_PROFILE_SUCCESS";
export const ADD_CHANNEL_PARTNER_PROFILE_FAIL =
  "ADD_CHANNEL_PARTNER_PROFILE_FAIL";

export const GET_SINGLE_CHANNEL_PARTNER_PROFILE_REQUEST =
  "GET_SINGLE_CHANNEL_PARTNER_PROFILE_REQUEST";
export const GET_SINGLE_CHANNEL_PARTNER_PROFILE_SUCCESS =
  "GET_SINGLE_CHANNEL_PARTNER_PROFILE_SUCCESS";
export const GET_SINGLE_CHANNEL_PARTNER_PROFILE_FAIL =
  "GET_SINGLE_CHANNEL_PARTNER_PROFILE_FAIL";

export const UPDATE_CHANNEL_PARTNER_PROFILE_REQUEST =
  "UPDATE_CHANNEL_PARTNER_PROFILE_REQUEST";
export const UPDATE_CHANNEL_PARTNER_PROFILE_SUCCESS =
  "UPDATE_CHANNEL_PARTNER_PROFILE_SUCCESS";
export const UPDATE_CHANNEL_PARTNER_PROFILE_FAIL =
  "UPDATE_CHANNEL_PARTNER_PROFILE_FAIL";
export const SET_RESPONSE = "SET_RESPONSE";
