export const MAIN_CATEGORY_LIST_REQUEST = "MAIN_CATEGORY_LIST_REQUEST";
export const MAIN_CATEGORY_LIST_SUCCESS = "MAIN_CATEGORY_LIST_SUCCESS";
export const MAIN_CATEGORY_LIST_FAILS = "MAIN_CATEGORY_LIST_FAILS";

export const MAIN_CATEGORY_DETAILS_REQUEST = "MAIN_CATEGORY_DETAILS_REQUEST";
export const MAIN_CATEGORY_DETAILS_SUCCESS = "MAIN_CATEGORY_DETAILS_SUCCESS";
export const MAIN_CATEGORY_DETAILS_FAILS = "MAIN_CATEGORY_DETAILS_FAILS";
