export const PRODUCT_FIND_BY_PRICE_REQUEST =
  "PRODUCT_FIND_BY_PRICE_REQUEST";
export const PRODUCT_FIND_BY_PRICE_SUCCESS =
  "PRODUCT_FIND_BY_PRICE_SUCCESS";
export const PRODUCT_FIND_BY_PRICE_FAIL = "PRODUCT_FIND_BY_PRICE_FAIL";
