export const PRODUCT_FIND_BY_CATEGORY_REQUEST = "PRODUCT_FIND_BY_CATEGORY_REQUEST";
export const PRODUCT_FIND_BY_CATEGORY_SUCCESS = "PRODUCT_FIND_BY_CATEGORY_SUCCESS";
export const PRODUCT_FIND_BY_CATEGORY_FAIL = "PRODUCT_FIND_BY_CATEGORY_FAIL";
