export const SUB_CATEGORY_LIST_REQUEST = "SUB_CATEGORY_LIST_REQUEST";
export const SUB_CATEGORY_LIST_SUCCESS = "SUB_CATEGORY_LIST_SUCCESS";
export const SUB_CATEGORY_LIST_FAILS = "SUB_CATEGORY_LIST_FAILS";

export const SUB_CATEGORY_DETAILS_REQUEST = "SUB_CATEGORY_DETAILS_REQUEST";
export const SUB_CATEGORY_DETAILS_SUCCESS = "SUB_CATEGORY_DETAILS_SUCCESS";
export const SUB_CATEGORY_DETAILS_FAILS = "SUB_CATEGORY_DETAILS_FAILS";
